### ISSUE TITLE
cloudformation crowdstrike registration 

### ISSUE THREAD

**Issue by Gal-Shukrun** [CrowdStrike/aws-cspm-registration-cloudformation#12]
Hey,

I want to registered Falcon to my aws accounts. I want to do it on each account (not in aws organization) in cloudformation. I didn't know which template i need to use. 
Also there is a way to add the clinet_id and the secret not hardcoded? I'm going to run it with pipeline and not form the console. 

TNX

**Comment by ryanjpayne** [comment]
@Gal-Shukrun I can work on adding a single-account template.  To pass keys we normally build the templates to accept them via parameters, with NoEcho set to true for security.  You can pass the keys to the parameter when you call the template in your pipeline.  Does this satisfy your requirements?
